### ISSUE TITLE
windows drivers

### ISSUE THREAD

**Issue by djcyberdad** [gh0stless/SIDBlaster-USB-Tic-Tac-Edition#2]
Has ANYONE gotten Windows to install the driver for this???

I'm about to pull my hair out!!!

**Comment by gh0stless** [comment]
What do you mean? The FTDI driver or the hardsid.dll? On latest Win 10 the ftdi driver comes with windows update, check that.

**Comment by gh0stless** [comment]
If the hardsid.dll is the issue, remember only the 64bit Version of Vice and the 64 Bit Version of AIASS needs the 64 Bit Version of the DLL. All other programs the 32 Bit version.

**Comment by djcyberdad** [comment]
Yes, I am trying to install the x86 version, but I cannot impliment it with regsvr32, nor windows update. It just shows it as an "unknown device"
![image](https://user-images.githubusercontent.com/61449942/133598124-92abab22-2b65-4fd6-aa48-a013a0c5fc93.png)

**Comment by djcyberdad** [comment]
I cannot find it in the VICE options Drop downs as well

**Comment by djcyberdad** [comment]
I'll have to try again later today. but it's the hardsid.dll I think?

**Comment by djcyberdad** [comment]
![image](https://user-images.githubusercontent.com/61449942/133599601-d003eb3a-d8b1-401d-b1fe-8c3d5f4255c1.png)

**Comment by gh0stless** [comment]
Click on update Driver or check prefernce/update/optional updates

**Comment by djcyberdad** [comment]
it does not work when I do that, even when I tell it to look in the folders

**Comment by gh0stless** [comment]
Install "by hand": https://ftdichip.com/drivers/d2xx-drivers/

**Comment by djcyberdad** [comment]
wait, you meant in "Windows Updates"...theres an Ftdi update

**Comment by djcyberdad** [comment]
I thought that was for flashing the PIC

**Comment by gh0stless** [comment]
MS changed driver delivery a while ago. It was the same for me with a print driver where I didn't know.

**Comment by djcyberdad** [comment]
it is displaying as a serial converter I think...I should take the sid out for this next step if it's what I think it is...

**Comment by gh0stless** [comment]
serial converter is rigth

**Comment by gh0stless** [comment]
![grafik](https://user-images.githubusercontent.com/11757531/133601098-41767d68-e4f7-49b3-b7fe-406b128c1405.png)

**Comment by djcyberdad** [comment]
ok, so according to the manual I need to flash my device?

**Comment by djcyberdad** [comment]
wait I read that wrong

**Comment by djcyberdad** [comment]
Mine does not look like that whatsoever

**Comment by djcyberdad** [comment]
![image](https://user-images.githubusercontent.com/61449942/133601674-8261f102-71b0-4a5b-a8d8-fb2aa3f3083f.png)

**Comment by djcyberdad** [comment]
![image](https://user-images.githubusercontent.com/61449942/133601829-fe1ff715-da97-4433-880c-a9342a954351.png)

**Comment by djcyberdad** [comment]
im exhausted and my head hurts, I'll try again tomorrow

**Comment by gh0stless** [comment]
I just looked at it, (3.5) either it is no longer supported, or only via a commando line parameter. I will test this. I only use versions from 2.4 to 3.2 and they all work fine.

**Comment by gh0stless** [comment]
![grafik](https://user-images.githubusercontent.com/11757531/133603340-8492ad90-fb7c-46d9-bc0e-ad34a412d562.png)

OK 3.5 works to, just copy dll to bin folder

**Comment by djcyberdad** [comment]
Supurb. I'm in bed now, will check later

**Comment by djcyberdad** [comment]
hardsid.dll is in the same folder as x64sc.exe, and hardsid is not showing up in the SID portion of the AUDIO options menu

**Comment by djcyberdad** [comment]
did you tweak file at all? Should I use the Hardsid.dll from the github?

**Comment by gh0stless** [comment]
https://github.com/gh0stless/SIDBlaster-USB-Tic-Tac-Edition/tree/master/hardsid_library

v.515 should do the job.

**Comment by djcyberdad** [comment]
the option is still not there

**Comment by djcyberdad** [comment]
ok, I think I got it in VICE 3.2
now I just need to make it make some damn sounds, lol

**Comment by djcyberdad** [comment]
do you have a "sidplayer" you can recommend for basic testing?

**Comment by gh0stless** [comment]
I always recommend ACID64 Player for a first, quick test. But version 3.6.3! 4.0 no longer supports the hardsid things.

**Comment by gh0stless** [comment]
On the other hand, you should check the communication with the SIDBlastertool.exe. If the SIDBlaster tool can access the SIDBlaster, the other programs should also be able to do so.

**Comment by djcyberdad** [comment]
I am going to continue to communicate with you via the "info@crazymidi" email, is that okay?

**Comment by gh0stless** [comment]
OK

**Comment by djcyberdad** [comment]
WE HAVE LIFT OFF

**Comment by gh0stless** [comment]
Note on the new driver provision from Microsoft will be added in the manual.
